---
- name: "PLAY 1: Manage VPNs with eos_config and jinja2"
  hosts: arista_eos
  tasks:
    - name: "TASK 1: Apply IOS VPN config via SSH/CLI"
      eos_config:
        src: "templates/eos_vrfs.j2"
        save_when: changed
      notify: config_changed
      register: cli_result
  handlers:
    - name: "HANDLER 1: Display relevant changes"
      listen: config_changed
      debug:
        msg: "{{ cli_result.commands }}"
